tasks:
  - name: terraform
    init: |
      source ./bin/install_terraform_cli
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
       source ./bin/install_aws_cli
       source ./bin/generate_tfrc_credentials
vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform